export const DEPARTMENTS = [
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Artificial Intelligence",
  "Electrical Engineering",
  "Civil Engineering",
  "Biotechnology",
  "Environmental Sciences",
  "Pharmacy",
  "Medical Laboratory Technology",
  "Management Sciences",
  "Business Data Analytics",
  "Economics",
  "Development Studies",
  "English",
  "Psychology",
  "Mathematics",
  "Geology",
  "Chemistry",
  "Physics",
];
