import { stamp } from "./helpers";

/** Mirrors PastPaper in server/Model/pastpaper.model.js. */
export const paperSeed = [
  {
    subject: "Operating Systems",
    instructor: "Dr. Ayesha Khan",
    semester: "Semester 5",
    year: 2024,
    exam: "Final",
    hasSolution: true,
    batch: "BCS-2022",
    department: "Computer Science",
    fileName: "os-final-2024.pdf",
    originalName: "OS Final 2024.pdf",
    fileSize: 512000,
    createdAt: stamp(3, 2),
    updatedAt: null,
  },
  {
    subject: "Database Systems",
    instructor: "Dr. Bilal Ahmed",
    semester: "Semester 4",
    year: 2024,
    exam: "Mid",
    hasSolution: false,
    batch: "BCS-2023",
    department: "Computer Science",
    fileName: "db-mid-2024.pdf",
    originalName: "DB Mid 2024.pdf",
    fileSize: 286720,
    createdAt: stamp(7, 5),
    updatedAt: null,
  },
  {
    subject: "Computer Networks",
    instructor: "Ms. Hira Sadiq",
    semester: "Semester 6",
    year: 2023,
    exam: "Final",
    hasSolution: true,
    batch: "BCS-2021",
    department: "Computer Science",
    fileName: "networks-final-2023.pdf",
    originalName: "Networks Final 2023.pdf",
    fileSize: 640000,
    createdAt: stamp(15, 1),
    updatedAt: null,
  },
  {
    subject: "Data Structures",
    instructor: "Dr. Umar Farooq",
    semester: "Semester 3",
    year: 2025,
    exam: "Mid",
    hasSolution: false,
    batch: "BCS-2024",
    department: "Computer Science",
    fileName: "ds-mid-2025.pdf",
    originalName: "DS Mid 2025.pdf",
    fileSize: 198656,
    createdAt: stamp(1, 8),
    updatedAt: null,
  },
  {
    subject: "Software Engineering",
    instructor: "Dr. Sana Malik",
    semester: "Semester 6",
    year: 2022,
    exam: "Final",
    hasSolution: true,
    batch: "BCS-2020",
    department: "Computer Science",
    fileName: "se-final-2022.pdf",
    originalName: "SE Final 2022.pdf",
    fileSize: 458752,
    createdAt: stamp(29, 3),
    updatedAt: null,
  },
  {
    subject: "Data Analysis",
    instructor: "Dr. Nida Iqbal",
    semester: "Semester 7",
    year: 2025,
    exam: "Final",
    hasSolution: false,
    batch: "BCS-2024",
    department: "Computer Science",
    fileName: "data-analysis-final-2025.pdf",
    originalName: "Data Analysis Final 2025.pdf",
    fileSize: 372736,
    createdAt: stamp(6, 6),
    updatedAt: null,
  },
];
