import { day, stamp } from "./helpers";

/** Mirrors Project in server/Model/project.model.js, plus `student` (admin-only "assigned to"). */
export const projectSeed = [
  {
    title: "Campus Connect Portal",
    desc:
      "Resource-sharing portal for students with assignment, past paper and project uploads.",
    course: "CS405",
    subject: "Software Engineering",
    student: "Yawar Hussain",
    dueDate: day(14),
    status: "Pending",
    repo: "https://github.com/yawarhussain7/Campus_Connect",
    semester: "Semester 6",
    department: "Computer Science",
    fileName: null,
    originalName: null,
    fileSize: null,
    createdAt: stamp(5, 3),
    updatedAt: null,
  },
  {
    title: "Library Management System",
    desc: "Desktop application for issuing, returning and reserving books.",
    course: "CS302",
    subject: "Database Systems",
    student: "Hamza Tariq",
    dueDate: day(-8),
    status: "Submitted",
    repo: "https://github.com/example/library-management",
    semester: "Semester 4",
    department: "Computer Science",
    fileName: "library-system.zip",
    originalName: "Library System.zip",
    fileSize: 3145728,
    createdAt: stamp(26, 2),
    updatedAt: null,
  },
  {
    title: "Traffic Sign Classifier",
    desc: "Convolutional network trained on the GTSRB dataset with a small web demo.",
    course: "CS501",
    subject: "Machine Learning",
    student: "Fatima Noor",
    dueDate: day(-21),
    status: "Submitted",
    repo: null,
    semester: "Semester 7",
    department: "Computer Science",
    fileName: "traffic-classifier.ipynb",
    originalName: "Traffic Classifier.ipynb",
    fileSize: 891289,
    createdAt: stamp(34, 7),
    updatedAt: null,
  },
  {
    title: "Campus Bus Tracker",
    desc: "Live bus positions on a map with an ETA estimate per stop.",
    course: "CS401",
    subject: "Computer Networks",
    student: "Usman Javed",
    dueDate: day(4),
    status: "Pending",
    repo: "https://github.com/example/bus-tracker",
    semester: "Semester 6",
    department: "Computer Science",
    fileName: null,
    originalName: null,
    fileSize: null,
    createdAt: stamp(2, 5),
    updatedAt: null,
  },
  {
    title: "Compiler for a Toy Language",
    desc: "Lexer, parser and code generator for a small imperative language.",
    course: "CS406",
    subject: "Compiler Construction",
    student: "Zainab Ali",
    dueDate: day(-16),
    status: "Overdue",
    repo: null,
    semester: "Semester 7",
    department: "Computer Science",
    fileName: "toy-compiler.zip",
    originalName: "Toy Compiler.zip",
    fileSize: 1572864,
    createdAt: stamp(19, 4),
    updatedAt: null,
  },
  {
    title: "Attendance Analytics Dashboard",
    desc: "Term-wise attendance trends with exportable summary reports.",
    course: "CS501",
    subject: "Data Analysis",
    student: "Bilal Raza",
    dueDate: day(23),
    status: "Pending",
    repo: "https://github.com/example/attendance-analytics",
    semester: "Semester 8",
    department: "Computer Science",
    fileName: null,
    originalName: null,
    fileSize: null,
    createdAt: stamp(1, 2),
    updatedAt: null,
  },
];
