import { stamp } from "./helpers";

/** Mirrors Review in server/Model/review.model.js. */
export const reviewSeed = [
  {
    student: "Yawar Hussain",
    teacher: "Dr. Ayesha Khan",
    teacherRole: "Assistant Professor",
    campus: "Islamabad",
    courseCode: "CS305",
    courseName: "Operating Systems",
    rating: 5,
    comment:
      "Walks through scheduling algorithms with real traces and keeps a steady pace.",
    semester: "Spring 2026",
    createdAt: stamp(2, 4),
    updatedAt: null,
  },
  {
    student: "Hamza Tariq",
    teacher: "Dr. Bilal Ahmed",
    teacherRole: "Associate Professor",
    campus: "Lahore",
    courseCode: "CS302",
    courseName: "Database Systems",
    rating: 4,
    comment: "Strong lab sessions, though the theory slides move quickly.",
    semester: "Fall 2025",
    createdAt: stamp(9, 2),
    updatedAt: null,
  },
  {
    student: "Fatima Noor",
    teacher: "Ms. Hira Sadiq",
    teacherRole: "Lecturer",
    campus: "Islamabad",
    courseCode: "CS401",
    courseName: "Computer Networks",
    rating: 5,
    comment: "Packet-level demos made congestion control click for me.",
    semester: "Spring 2026",
    createdAt: stamp(4, 6),
    updatedAt: null,
  },
  {
    student: "Usman Javed",
    teacher: "Dr. Umar Farooq",
    teacherRole: "Professor",
    campus: "Wah",
    courseCode: "CS201",
    courseName: "Data Structures",
    rating: 3,
    comment: "Content is solid but the assignment feedback turnaround is slow.",
    semester: "Fall 2025",
    createdAt: stamp(17, 1),
    updatedAt: null,
  },
  {
    student: "Zainab Ali",
    teacher: "Dr. Sana Malik",
    teacherRole: "Assistant Professor",
    campus: "Islamabad",
    courseCode: "CS405",
    courseName: "Software Engineering",
    rating: 4,
    comment: "Sprint reviews are well organised and the rubrics are clear.",
    semester: "Spring 2026",
    createdAt: stamp(6, 3),
    updatedAt: null,
  },
  {
    student: "Bilal Raza",
    teacher: "Dr. Nida Iqbal",
    teacherRole: "Lecturer",
    campus: "Lahore",
    courseCode: "CS501",
    courseName: "Data Analysis",
    rating: 5,
    comment: "Notebooks and datasets are shared before every session.",
    semester: "Spring 2026",
    createdAt: stamp(11, 5),
    updatedAt: null,
  },
];
